api_platform:
    resource: .
    type: api_platform
    prefix: /api

get_appointments_patient:
    path: '/api/appointments/patient/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']