api_platform:
    resource: .
    type: api_platform
    prefix: /api

get_appointments_patient:
    path: '/api/appointments/patient/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']


get_treatment_patient:
    path: '/api/treatments/patient/{id}'
    controller: App\Controller\TreatmentController::getPatientWithTreatments
    methods: ['GET']

post_treatment_patient:
    path: '/api/treatments/add/patient/{id}'
    controller: App\Controller\TreatmentController::addTreatment
    methods: ['POST']

delete_treatment_patient:
    path: '/api/treatments/delete/{treatmentid}/patient/{patientid}'
    controller: App\Controller\TreatmentController::deleteTreatment
    methods: ['DELETE']