api_platform:
    resource: .
    type: api_platform
    prefix: /api

<<<<<<<<< Temporary merge branch 1
get_patient_and_appointment:
    path: '/api/appointments/patient/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']

<<<<<<<<< Temporary merge branch 1
get_patient:
    path: '/api/patients'
    controller: App\Controller\PatientController::getAllPatients  
    methods: ['GET']

# add_patient:
#     path: '/api/patients/add'
#     controller: App\Controller\AddPatientController::addPatient
#     methods: ['POST']

delete_patient:
    path: 'api/patients/{id}'
    controller: App\Controller\DeletePatientController::deletePatient
    methods: ['DELETE']
=========
get_user:
    path: '/api/users/{id}'
    controller: App\Controller\ProfilController::getuserdataProfil
    methods: ['GET']

post_login:
    path: '/api/login'
    controller: App\Controller\LoginController::post_login
    methods: ['POST']
