api_platform:
    resource: .
    type: api_platform
    prefix: /api

get_patient_and_appointment:
    path: '/api/appointments/patient/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']

get_patient:
    path: '/api/patients'
    controller: App\Controller\PatientController::getAllPatients  
    methods: ['GET']  

add_patient:
    path: '/api/patients/add'
    controller: App\Controller\AddPatientController::addPatient
    methods: ['POST']

delete_patient:
    path: 'api/patients/{id}'
    controller: App\Controller\DeletePatientController::deletePatient
    methods: ['DELETE']
