api_platform:
    resource: .
    type: api_platform
    prefix: /api

# Api Routes Appointments
get_patient_and_appointment:
    path: '/api/patient/appointments/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']

post_appointment:
    path: '/api/appointments/add/{id}'
    controller: App\Controller\AppointmentController::addAppointment
    methods: ['POST']

# Api Routes Patients
get_patient:
    path: '/api/patients'
    controller: App\Controller\PatientController::getAllPatients  
    methods: ['GET']

add_patient:
    path: '/api/patients/add'
    controller: App\Controller\AddPatientController::AddPatient
    methods: ['POST']

# Api Routes Authentification
get_user:
    path: '/api/users/{id}'
    controller: App\Controller\ProfilController::getuserdataProfil
    methods: ['GET']

post_login:
    path: '/api/login'
    controller: App\Controller\LoginController::post_login
    methods: ['POST']

# Api Routes Treatments
get_treatment_patient:
    path: '/api/patient/treatments/{id}'
    controller: App\Controller\TreatmentController::getPatientWithTreatments
    methods: ['GET']

post_treatment_patient:
    path: '/api/patient/treatments/add/{id}'
    controller: App\Controller\TreatmentController::addTreatment
    methods: ['POST']

delete_treatment_patient:
    path: '/api/treatments/delete/{treatmentid}/patient/{patientid}'
    controller: App\Controller\TreatmentController::deleteTreatment
    methods: ['DELETE']

update_treatment_patient:
    path: '/api/treatments/update/{treatmentid}/patient/{patientid}'
    controller: App\Controller\TreatmentController::updateTreatment
    methods: ['PUT']

get_one_treatment:
    path: '/api/treatments/{id}'
    controller: App\Controller\TreatmentController::getOneTreatment
    methods: ['GET']
