api_platform:
    resource: .
    type: api_platform
    prefix: /api

# get_appointments_patient:

get_patient_and_appointment:
    path: '/api/appointments/patient/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']


get_treatment_patient:
    path: '/api/treatments/patient/{id}'
    controller: App\Controller\TreatmentController::getPatientWithTreatments
    methods: ['GET']

post_treatment_patient:
    path: '/api/treatments/add/patient/{id}'
    controller: App\Controller\TreatmentController::addTreatment
    methods: ['POST']

delete_treatment_patient:
    path: '/api/treatments/delete/{treatmentid}/patient/{patientid}'
    controller: App\Controller\TreatmentController::deleteTreatment
    methods: ['DELETE']

update_treatment_patient:
    path: '/api/treatments/update/{treatmentid}/patient/{patientid}'
    controller: App\Controller\TreatmentController::updateTreatment
    methods: ['PUT']

get_one_treatment:
    path: '/api/treatments/{id}'
    controller: App\Controller\TreatmentController::getOneTreatment
    methods: ['GET']

get_all_patient:
    path: '/api/patients'
    controller: App\Controller\PatientController::getAllPatients  
    methods: ['GET']

# add_patient:
#     path: '/api/patients/add'
#     controller: App\Controller\AddPatientController::addPatient
#     methods: ['POST']

# delete_patient:
#     path: 'api/patients/{id}'
#     controller: App\Controller\DeletePatientController::deletePatient
#     methods: ['DELETE']
