api_platform:
    resource: .
    type: api_platform
    prefix: /api

get_appointments_patient:
    path: '/api/appointments/patient/{id}'
    controller: App\Controller\AppointmentController::getPatientWithAppointments
    methods: ['GET']

get_appointment:
    path: '/api/appointments'
    controller: App\Controller\AppointmentController::getAllAppointments
    methods: ['GET']

get_user:
    path: '/api/users'
    controller: App\Controller\ProfilController::getuserdataProfil
    methods: ['GET']

post_login:
    path: '/api/login'
    controller: App\Controller\LoginController::post_login
    methods: ['POST']